export const UserActionTypes = {
  SIGN_WITH_EMAIL_START: "SIGN_WITH_EMAIL_START",
  SIGN_WITH_EMAIL_SUCCES: "SIGN_WITH_EMAIL_SUCCES",
  SIGN_WITH_EMAIL_FAIL: "SIGN_WITH_EMAIL_FAIL",

  SIGN_WITH_GOOGLE_START: "SIGN_WITH_GOOGLE_START",
  SIGN_WITH_GOOGLE_SUCCES: "SIGN_WITH_GOOGLE_SUCCES",
  SIGN_WITH_GOOGLE_FAIL: "SIGN_WITH_GOOGLE_FAIL",
};
