export const UserActionTypes = {
  SIGN_WITH_EMAIL_START: "SIGN_WITH_EMAIL_START",
  SIGN_WITH_GOOGLE_START: "SIGN_WITH_GOOGLE_START",
  SIGN_IN_SUCCES: "SIGN_IN_SUCCES",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  CREATE_PROFILE_ACCOUNT: "CREATE_PROFILE_ACCOUNT",
};
